---
title: "Dijkstra-algorithm"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(seoulsubway)
library(igraph)
library(geosphere)
```

## 다익스트라 알고리즘 구현을 위한 네트워크 구축
```{r}
# 필요데이터 
data("subway_data")
data("seoul_station")
data("subway_data_DT")
data("transfer_station")
seoul_station
mat <- data.frame(matrix(Inf,468,468))
colnames(mat) <- rownames(mat) <- seoul_station

for(i in 1:468){
  mat[i,i] <- 0
}

nm<-"거여"
nm<-"가양"
nm_dist <- function(nm){
  Line <- subway_data_DT[which(subway_data_DT$Name==nm),]$Line[1]
  n <- nrow(subway_data[[Line]])
  ind <- which(subway_data[[Line]]$Name==nm)
  if(ind==1){
  UD <- subway_data[[Line]][c(which(subway_data[[Line]]$Name==nm),
                        which(subway_data[[Line]]$Name==nm)+1),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  re <- rbind(c(UD[1,"Name"], result1))
  }
  if(ind==n){
  UD <- subway_data[[Line]][c(which(subway_data[[Line]]$Name==nm)-1,
                             which(subway_data[[Line]]$Name==nm)),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  re <- rbind(c(UD[1,"Name"], result1))
  }
  if(isTRUE(ind%in%c(1,n))==FALSE){
  UD <- subway_data[[Line]][c(which(subway_data[[Line]]$Name==nm)-1,
                      which(subway_data[[Line]]$Name==nm),
                      which(subway_data[[Line]]$Name==nm)+1),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  UD_3 <- UD[3, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  result2 <- distHaversine(as.numeric(UD_2), as.numeric(UD_3))
  re <- rbind(c(UD[1,"Name"], result1), c(UD[3,"Name"], result2))
  }
  return(re)
}

nm_dist(rownames(mat)[1])
mat[1, which(rownames(mat)%in%nm_dist(rownames(mat)[1])[1,1])] <- nm_dist(rownames(mat)[1])[1,2]
mat[1, which(rownames(mat)%in%nm_dist(rownames(mat)[1])[2,1])] <- nm_dist(rownames(mat)[1])[2,2]

nm_list_index_null <- which(seoul_station%in%transfer_station$Name)
nm_list <- seoul_station[-nm_list_index_null]
nm_list_index <- which(seoul_station%in%nm_list)

for(i in 1:length(nm_list_index)){
  if(nrow(nm_dist(rownames(mat)[nm_list_index[i]]))==2){
  mat[nm_list_index[i], which(rownames(mat)%in%nm_dist(rownames(mat)[nm_list_index[i]])[1,1])] <- nm_dist(rownames(mat)[nm_list_index[i]])[1,2]
  mat[nm_list_index[i], which(rownames(mat)%in%nm_dist(rownames(mat)[nm_list_index[i]])[2,1])] <- nm_dist(rownames(mat)[nm_list_index[i]])[2,2]
  }
  if(nrow(nm_dist(rownames(mat)[nm_list_index[i]]))==1){
    mat[nm_list_index[i], which(rownames(mat)%in%nm_dist(rownames(mat)[nm_list_index[i]])[1,1])] <- nm_dist(rownames(mat)[nm_list_index[i]])[1,2]
  }
}

head(mat)

nm <- "가락시장"
nm_dist_tr <- function(nm){
  Line <- subway_data_DT[which(subway_data_DT$Name==nm),]$Line
  re<-list()
  for(i in 1:length(Line)){
  n <- nrow(subway_data[[Line[i]]])
  ind <- which(subway_data[[Line[i]]]$Name==nm)
  if(ind==1){
  UD <- subway_data[[Line[i]]][c(which(subway_data[[Line[i]]]$Name==nm),
                        which(subway_data[[Line[i]]]$Name==nm)+1),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  re[[i]] <- rbind(c(UD[1,"Name"], result1))
  }
  if(ind==n){
  UD <- subway_data[[Line[i]]][c(which(subway_data[[Line[i]]]$Name==nm)-1,
                             which(subway_data[[Line[i]]]$Name==nm)),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  re[[i]] <- rbind(c(UD[1,"Name"], result1))
  }
  if(isTRUE(ind%in%c(1,n))==FALSE){
  UD <- subway_data[[Line[i]]][c(which(subway_data[[Line[i]]]$Name==nm)-1,
                      which(subway_data[[Line[i]]]$Name==nm),
                      which(subway_data[[Line[i]]]$Name==nm)+1),]
  UD_1 <- UD[1, c("long", "lat")]
  UD_2 <- UD[2, c("long", "lat")]
  UD_3 <- UD[3, c("long", "lat")]
  result1 <- distHaversine(as.numeric(UD_1), as.numeric(UD_2))
  result2 <- distHaversine(as.numeric(UD_2), as.numeric(UD_3))
  re[[i]] <- rbind(c(UD[1,"Name"], result1), c(UD[3,"Name"], result2))
  }
  }
  return(re)
}
nm_dist_tr("가락시장")
for(i in 1:length(nm_list_index_null)){
  for(j in 1:length(nm_dist_tr(rownames(mat)[nm_list_index_null[i]]))){
    if(nrow(nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]])==2){
  mat[nm_list_index_null[i], which(rownames(mat)%in%nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][1,1])] <- nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][1,2]
  mat[nm_list_index_null[i], which(rownames(mat)%in%nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][2,1])] <- nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][2,2]
  }
  if(nrow(nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]])==1){
    mat[nm_list_index_null[i], which(rownames(mat)%in%nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][1,1])] <- nm_dist_tr(rownames(mat)[nm_list_index_null[i]])[[j]][1,2]
  }
  }
}

mat[mat==Inf] <- 0
subway_data[["6-A"]]$Name
mat[which(rownames(mat)=="응암"),"응암"]<-0
nm_dist_tr("응암")
mat <- as.matrix(mat)
g <- graph.adjacency(mat, weighted = TRUE)
s.paths <- shortest.paths(g, algorithm = "dijkstra", mode=c("all"))


# 468X468 소요거리 모두 포함되어있는 219024개의 요소가 포함된 매트릭스구조
s.paths_div_time <- s.paths/566

shortest.paths

plot(g)
.Call(C_R_igraph_shortest_paths)
```