---
title: "Make the key set of the path"
output: html_document
editor_options: 
  chunk_output_type: console
---


## load packages
```{r}
#devtools::install_github("king4k1/seoulsubway")
library(seoulsubway)
library(data.table)
library(dplyr)
library(stringr)
data("subway_data_DT")
```

## get station_name vector for construct matrix
```{r}
transaction_data <- fread(file=file.choose(), encoding = "UTF-8")
# choose transaction data

seoul_route <- transaction_data%>%select(승차역명, 승차호선명)
seoul_route <- unique(seoul_route)
ind1 <- str_locate(seoul_route$승차역명, "[(]")
ind <- ind1[-which(is.na(ind1[,1])),1]
ind2 <- which(is.na(ind1[,1])==TRUE)
seoul_route$승차역명[-ind2] <- str_sub(seoul_route$승차역명[-ind2], 1, ind-1)
seoul_route$승차역명 <- str_replace(seoul_route$승차역명, "서울역", "서울")
seoul_route$승차역명 <- str_replace(seoul_route$승차역명, "이수", "총신대입구")
seoul_route$승차호선명 <- str_sub(seoul_route$승차호선명, 1, 1)
colnames(seoul_route) <- c("Name", "Line")
ind_2_A <- which(seoul_route$Name %in% c("용답","신답","용두","신설동"))
ind_2_B <- which(seoul_route$Name %in% c("도림천","양천구청","신정네거리","까치산"))
ind_5_A <- which(seoul_route$Name %in% c("둔촌동","올림픽공원","방이", "오금","개롱","거여","마천"))
ind_6_A <- which(seoul_route$Name %in% c("역촌","독바위","구산"))
seoul_route[ind_2_A,]$Line <- "2-A"
seoul_route[ind_2_B,]$Line <- "2-B"
seoul_route[ind_5_A,]$Line <- "5-A"
seoul_route[ind_6_A,]$Line <- "6-A"
seoul_route[seoul_route$Name=="신설동"][1]$Line <- "1" # 신설동역 2가지 호선에 대하여 하나는 1호선으로 표기 필요
head(seoul_route)

seoul_station <- subway_data_DT$Name
seoul_station <- sort(unique(seoul_station))
subway_make_list <- data.frame(matrix(0,1,460))
colnames(subway_make_list) <- seoul_station
head(subway_make_list)

```


## function to get route : get_path()

```{r}
depart <- seoul_route[1,]$Name ; depart_line <- seoul_route[1,]$Line
arrival <- seoul_route[2,]$Name ; arrival_line <- seoul_route[2,]$Line

get_path<- function(depart, depart_line, arrival, arrival_line){
result <- shortestpath(depart, depart_line, arrival, arrival_line)

if(result$Time==300){
  Path <- "no result"
  ind <- 0
  result$Info <- data.frame(matrix(0,5,5))
}
if(result$Time!=300 & nrow(result$Info)==1){
  Path <- result$Path
  Path <- Path$Name
  ind <- which(seoul_station%in%Path)
}
if(result$Time!=300 & nrow(result$Info)==2){
  Path <- rbind(result$Path1, result$Path2)
  Path <- Path[-which(duplicated(Path$Name)),]$Name
  ind <- which(seoul_station%in%Path)
}
if(result$Time!=300 & nrow(result$Info)==3){
  Path <- rbind(result$Path1, result$Path2, result$Path3)
  Path <- Path[-which(duplicated(Path$Name)),]$Name
  ind <- which(seoul_station%in%Path)
}
if(result$Time!=300 & nrow(result$Info)==4){
  Path <- rbind(result$Path1, result$Path2, result$Path3, result$Path4)
  Path <- Path[-which(duplicated(Path$Name)),]$Name
  ind <- which(seoul_station%in%Path)
}
return(data.frame(Path, ind))
}

get_path(depart="봉화산", depart_line="6",
                       arrival="강동", arrival_line="5-A")
```


## get list format R data

```{r}
seoul_route <- seoul_route%>%arrange(Name)
subway_route2 <- list()
for(i in 1:276){
  for(j in (i+1):277){
    subway_route2[[paste0(seoul_route[i,]$Name,"(",seoul_route[i,]$Line,")",
                            "-",seoul_route[j,]$Name,"(",seoul_route[j,]$Line,")")]] <- get_path(depart=seoul_route[i,]$Name, depart_line=seoul_route[i,]$Line,
                       arrival=seoul_route[j,]$Name, arrival_line=seoul_route[j,]$Line)
  }
  if(i %in% c(10*(1:25),277)){
    save(file="D:/subway_analysis/data/subway_route2.RData",subway_route2, seoul_route)
  }
}

```


## handling for complete data set

```{r, eval= FALSE}
load("D:/subway_analysis/subway_route.RData")
find_null <- rep(0,37600)
for(i in 1:37600){
  find_null[i] <- nrow(subway_route2[[i]])
}

null_set <- find_null[which(find_null==1)]
null_set_list <- rep(0,418)
for(i in 1:418){
null_set_list[i] <- isTRUE(subway_route2[[which(find_null==1)[i]]][1,1]=="no result")
}
null_index <- which(find_null==1)[null_set_list==1]
null_route_name <-names(subway_route2)[null_index]
null_route <- as.data.frame(null_route_name)
str_split(null_route$null_route, pattern="[(a)]", n=4)
str_locate(null_route$null_route, "[-]")

null_route <- separate(null_route, null_route, c("depart","depart_line","arrival", "arrival_line"), sep="[(a)]")
null_route$arrival <- str_remove(null_route$arrival, "-")
for(i in 1:385){
subway_route2[[]] <- shortestpath_3(null_route$depart[i], null_route$depart_line[i], null_route$arrival[i], null_route$arrival_line[i])
}

```

```{r}

# shortestpath_3

shortestpath_3 <- function(depart, depart_line, arrival, arrival_line) {
  data("subway_data", envir = environment())
  data("transfer_info", envir = environment())
  # load data
  Total_Depart_Raw <- nrow(subway_data[[depart_line]])
  Total_End_raw <- nrow(subway_data[[arrival_line]])
  Start_Ind_3 <- which(subway_data[[depart_line]]$Name == depart)
  Transfer_List <- get_transferinfo(depart, depart_line, arrival, arrival_line, 
                                    count = 3)
  Transfer_3 <- list()
  # get available transfer station list these results are list format and
  # get first/second transfer station
  for (i in seq_along(Transfer_List)) {
    Transfer_First <- Transfer_List[[i]]$first
    Transfer_Second <- Transfer_List[[i]]$second
    Transfer_Third <- Transfer_List[[i]]$third
    End_Ind_3 <- which(subway_data[[depart_line]]$Name == Transfer_First$Name)
    Transfer_First_Ind <- str_split(Transfer_First$Transfer, paste0("[", 
                                                                    "$", "|", "]"))[[1]]
    Transfer_Second_Ind <- str_split(Transfer_Second$Transfer, paste0("[", 
                                                                      "$", "|", "]"))[[1]]
    Transfer_Third_Ind <- str_split(Transfer_Third$Transfer, paste0("[", 
                                                                    "$", "|", "]"))[[1]]    
    # process variable for get transfer line
    Transfer_First_Line <- Transfer_Second_Ind[which(Transfer_Second_Ind%in%Transfer_First_Ind)][1]
    Transfer_Second_Line <- Transfer_Third_Ind[which(Transfer_Third_Ind%in%Transfer_Second_Ind)][1]
    Transfer_Third_Line <- arrival_line
    Total_Transfer1_Raw <- nrow(subway_data[[Transfer_First_Line]])
    Total_Transfer2_Raw <- nrow(subway_data[[Transfer_Second_Line]])
    Start_Ind2_3 <- which(subway_data[[Transfer_First_Line]]$Name == Transfer_First$Name)
    End_Ind2_3 <- which(subway_data[[Transfer_First_Line]]$Name == Transfer_Second$Name)
    Start_Ind3_3 <- which(subway_data[[Transfer_Second_Line]]$Name == Transfer_Second$Name)
    End_Ind3_3 <- which(subway_data[[Transfer_Second_Line]]$Name == Transfer_Third$Name)
    Start_Ind4_3 <- which(subway_data[[arrival_line]]$Name == Transfer_Third$Name)
    End_Ind4_3 <- which(subway_data[[arrival_line]]$Name == arrival)
    # get information about each path way
    Path1_Info <- get_pathinfo(total = Total_Depart_Raw, ind1 = Start_Ind_3, 
                               ind2 = End_Ind_3, line = depart_line)
    Path1_Count <- as.numeric(Path1_Info["count"])
    Path1_Time <- as.numeric(Path1_Info["time"])
    Path2_Info <- get_pathinfo(total = Total_Transfer1_Raw, ind1 = Start_Ind2_3, 
                               ind2 = End_Ind2_3, line = Transfer_First_Line)
    Path2_Count <- as.numeric(Path2_Info["count"])
    Path2_Time <- as.numeric(Path2_Info["time"])
    Path3_Info <- get_pathinfo(total = Total_Transfer2_Raw, ind1 = Start_Ind3_3, 
                               ind2 = End_Ind3_3, line = Transfer_Second_Line)
    Path3_Count <- as.numeric(Path3_Info["count"])
    Path3_Time <- as.numeric(Path3_Info["time"])
    Path4_Info <- get_pathinfo(total = Total_End_raw, ind1 = Start_Ind4_3, 
                               ind2 = End_Ind4_3, line = arrival_line)
    Path4_Count <- as.numeric(Path4_Info["count"])
    Path4_Time <- as.numeric(Path4_Info["time"])    
    # get transfer time{ex) depart -> transfer} each
    Transfer_Time1_List <- transfer_info[which(transfer_info$Transfer_Name == 
                                                 Transfer_First$Name), ]
    Transfer_Time1_T <- Transfer_Time1_List[which(Transfer_Time1_List$Transfer_Line == 
                                                    depart_line), ]
    Transfer_Time1 <- Transfer_Time1_T[which(Transfer_Time1_T$Transfer_Line2 == 
                                               Transfer_First_Line), ]
    Transfer_Time2_List <- transfer_info[which(transfer_info$Transfer_Name == 
                                                 Transfer_Second$Name), ]
    Transfer_Time2_T <- Transfer_Time2_List[which(Transfer_Time2_List$Transfer_Line == 
                                                    Transfer_First_Line), ]
    Transfer_Time2 <- Transfer_Time2_T[which(Transfer_Time2_T$Transfer_Line2 == 
                                               Transfer_Second_Line), ]
    Transfer_Time3_List <- transfer_info[which(transfer_info$Transfer_Name == 
                                                 Transfer_Third$Name), ]    
    Transfer_Time3_T <- Transfer_Time3_List[which(Transfer_Time3_List$Transfer_Line == 
                                                    Transfer_Second_Line), ]
    Transfer_Time3 <- Transfer_Time3_T[which(Transfer_Time3_T$Transfer_Line2 == 
                                               arrival_line), ]
    if (nrow(Transfer_Time1) >= 1) {
      Transfer_Time1 <- as.numeric(Transfer_Time1$Transfer_Time)
    } else {
      Transfer_Time1 <- 2.35
    }
    # if no results about transfer_info data -> print 2.35(citation)
    if (nrow(Transfer_Time2) >= 1) {
      Transfer_Time2 <- as.numeric(Transfer_Time2$Transfer_Time)
    } else {
      Transfer_Time2 <- 2.35
    }
    if (nrow(Transfer_Time3) >= 1) {
      Transfer_Time3 <- as.numeric(Transfer_Time3$Transfer_Time)
    } else {
      Transfer_Time3 <- 2.35
    }
    Transfer_3[[i]] <- list(Info = data.frame(Depart = c(depart, Transfer_First$Name, Transfer_Second$Name, Transfer_Third$Name),
                                              Line = c(depart_line, Transfer_First_Line, Transfer_Second_Line, arrival_line), 
                                              Count = c(as.numeric(Path1_Count), as.numeric(Path2_Count), as.numeric(Path3_Count), as.numeric(Path4_Count)),
                                              Time = c(as.numeric(Path1_Time), as.numeric(Path2_Time), as.numeric(Path3_Time), as.numeric(Path4_Time)),
                                              Arrive = c(Transfer_First$Name, Transfer_Second$Name, Transfer_Third$Name, arrival)),
                            Total = c(Count = sum(Path1_Count + Path2_Count + Path3_Count + Path4_Count), 
                                      Time = sum(Path1_Time + Path2_Time + Path3_Time + Path4_Time) + Transfer_Time1 + Transfer_Time2 + Transfer_Time3 + 9))
    
  }
  Transfer_3_Count_Time <- c()
  for (i in seq_along(Transfer_3)) {
    Transfer_3_Count_Time[i] <- as.numeric(Transfer_3[[i]]["Total"][[1]]["Time"])
  }
  Path_3_Shortest <- which.min(Transfer_3_Count_Time)
  # select shortest path(time depend)
  Transfer_3 <- Transfer_3[[Path_3_Shortest]]
  Set <- list(Info = Transfer_3$Info, Count = as.numeric(Transfer_3["Total"][[1]]["Count"]), 
              Time = as.numeric(Transfer_3["Total"][[1]]["Time"]))
  End_Ind_3 <- which(subway_data[[depart_line]]$Name == as.character(Set["Info"][[1]][1, "Arrive"]))
  Start_Ind2_3 <- which(subway_data[[as.character(Set["Info"][[1]][2, "Line"])]]$Name == as.character(Set["Info"][[1]][2, "Depart"]))
  End_Ind2_3 <- which(subway_data[[as.character(Set["Info"][[1]][2, "Line"])]]$Name == 
                        as.character(Set["Info"][[1]][2, "Arrive"]))
  End_Ind3_3 <- which(subway_data[[as.character(Set["Info"][[1]][3, "Line"])]]$Name == 
                        as.character(Set["Info"][[1]][3, "Arrive"]))
  Start_Ind3_3 <- which(subway_data[[as.character(Set["Info"][[1]][3, "Line"])]]$Name == as.character(Set["Info"][[1]][3, 
                                                                                          "Depart"]))
  Start_Ind4_3 <- which(subway_data[[arrival_line]]$Name == as.character(Set["Info"][[1]][4, 
                                                                                          "Depart"]))
  
  Set$Path1 <- subway_data[[depart_line]][Start_Ind_3:End_Ind_3, ]
  Set$Path2 <- subway_data[[as.character(Set["Info"][[1]][2, "Line"])]][Start_Ind2_3:End_Ind2_3, ]
  Set$Path3 <- subway_data[[as.character(Set["Info"][[1]][3, "Line"])]][Start_Ind3_3:End_Ind3_3, ]
  Set$Path4 <- subway_data[[as.character(Set["Info"][[1]][4, "Line"])]][Start_Ind4_3:End_Ind4_3, ]
  
  if (isTRUE(depart_line == 2) & isTRUE(depart_line == (Total_Depart_Raw - Start_Ind_3 + End_Ind_3))) {
    Set$Path1 <- subway_data[["2"]][c(Start_Ind_3:Total_Depart_Raw, 1:End_Ind_3), ]
  } else if (isTRUE(depart_line == 2) & isTRUE(depart_line == (Total_Depart_Raw - 
                                                               End_Ind_3 + Start_Ind_3))) {
    Set$Path1 <- subway_data[["2"]][c(End_Ind_3:Total_Depart_Raw, 1:Start_Ind_3), ]
  }
  if (isTRUE(Set["Info"][[1]][2, "Line"] == 2) & isTRUE(Set["Info"][[1]][2, 
                                                                         "Count"] == (Total_Transfer1_Raw - Start_Ind2_3 + End_Ind2_3))) {
    Set$Path2 <- subway_data[["2"]][c(Start_Ind2_3:Total_Transfer1_Raw, 1:End_Ind2_3), ]
  } else if (isTRUE(Set["Info"][[1]][2, "Line"] == 2) & isTRUE(Set["Info"][[1]][2, 
                                                                                "Count"] == (Total_Transfer1_Raw - End_Ind2_3 + Start_Ind2_3))) {
    Set$Path2 <- subway_data[["2"]][c(End_Ind2_3:Total_Transfer1_Raw, 1:Start_Ind2_3), ]
  }
  if (isTRUE(arrival_line == 2) & isTRUE(Set["Info"][[1]][3, "Count"] == 
                                         (Total_Transfer2_Raw - Start_Ind3_3 + End_Ind3_3))) {
    Set$Path3 <- subway_data[["2"]][c(Start_Ind3_3:Total_Transfer2_Raw, 1:End_Ind3_3), ]
  } else if (isTRUE(arrival_line == 2) & isTRUE(Set["Info"][[1]][3, "Count"] == 
                                                (Total_Transfer2_Raw - End_Ind3_3 + Start_Ind3_3))) {
    Set$Path3 <- subway_data[["2"]][c(End_Ind3_3:Total_Transfer2_Raw, 1:Start_Ind3_3), ]
  }
  if (isTRUE(arrival_line == 2) & isTRUE(Set["Info"][[1]][3, "Count"] == 
                                         (Total_End_raw - Start_Ind4_3 + End_Ind4_3))) {
    Set$Path4 <- subway_data[["2"]][c(Start_Ind3_3:Total_End_raw, 1:End_Ind4_3), ]
  } else if (isTRUE(arrival_line == 2) & isTRUE(Set["Info"][[1]][3, "Count"] == 
                                                (Total_End_raw - End_Ind4_3 + Start_Ind4_3))) {
    Set$Path4 <- subway_data[["2"]][c(End_Ind4_3:Total_End_raw, 1:Start_Ind4_3), ]
  }
  # consider line number 2 for circulate system.
  return(Set)
}

```